### PR TITLE
Fix decoding issue with ZICOND extension

### PR DESCRIPTION
**Pull request by austinfoo**

### CODE REVIEW

**Review by jeffnye-gh — CHANGES_REQUESTED** [review]
Your tests use the Andes API, zicond is not an Andes extension.

**Comment by austinfoo** [comment]
Where do you want the zicond tests? tests/condor? tests/riscv-tests/isa? somewhere else?

**Comment by jeffnye-gh** [comment]
I'm asking you to change the test wrapper API to use the riscv-isa-tests API. Location is fine.

**Comment by austinfoo** [comment]
@jeffnye-gh, here is the updated PR

**Review by jeffnye-gh — APPROVED** [review]

**Pull request merged**
